version: "3.8"

services:
  be:
    image: node:15
    volumes:
      - .:/app
    user: "1000:1000"
    tty: true
    depends_on:
      - mysql
    ports:
      - 3000:3000
    working_dir: /app
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
